apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    nodePoolName: {{ .Values.nodePoolName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
    nodePoolName: {{ .Values.nodePoolName }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
