apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.name }}
  ports:
  - name: api
    port: {{ .Values.ports.http }}
    targetPort: api
  - name: rpc
    port: {{ .Values.ports.rpc }}
    targetPort: rpc
